const postActionTypes = {
  GET_POSTS_FEED_START: "GET_POSTS_FEED_START",
  GET_POSTS_FEED_SUCCESS: "GET_POSTS_FEED_SUCCESS",
  GET_POSTS_FEED_FAILURE: "GET_POSTS_FEED_FAILURE",
  GET_POSTS_START: "GET_POSTS_START",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_FAILURE: "GET_POSTS_FAILURE",
  GET_POST_START: "GET_POST_START",
  GET_POST_SUCCESS: "GET_POST_SUCCESS",
  GET_POST_FAILURE: "GET_POST_FAILURE",
  CREATE_POST_START: "CREATE_POST_START",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILURE: "CREATE_POST_FAILURE",
  LIKE_POST: "LIKE_POST",
  LIKE_POST_ERROR: "LIKE_POST_ERROR",
  UNLIKE_POST: "UNLIKE_POST",
  UNLIKE_POST_ERROR: "UNLIKE_POST_ERROR",
  COMMENT_POST: "COMMENT_POST",
  COMMENT_POST_FAILURE: "COMMENT_POST_FAILURE",
  UNCOMMENT_POST: "UNCOMMENT_POST",
  UNCOMMENT_POST_SUCCESS: "UNCOMMENT_POST_SUCCESS",
  UNCOMMENT_POST_FAILURE: "UNCOMMENT_POST_FAILURE",
  DELETE_POST: "DELETE_POST",
  DELETE_POST_FAILURE: "DELETE_POST_FAILURE",
  CLEAR_POSTS: "CLEAR_POSTS"
};

export default postActionTypes;
